### PR TITLE
Fix hex code generation

### LINKED ISSUE #29: Generation of hex codes
Leading 0s are disregarded by the JavaScript interpreter and therefore can the function currently being used can generate incomplete hex codes of only five characters.

### LINKED ISSUE #33: Local Storage
Allow a user to stay logged on using local storage

### PR DESCRIPTION
**Pull request by sschipke**
## What's this PR do?
- Fixes hex code generation
- Utilizes local storage when a user signs up or logins in 
### Where should the reviewer start?
- App
- Login Form
- Sign Up Form

### How should this be manually tested?
Pull down this branch locally and run `npm run` sign up or login, refresh the page and see if your account persists
### What are the relevant tickets?
closes #31 closes #33 closes #29

### CODE REVIEW

File: src/components/PaletteContainer/PaletteContainer.js [hunk 1]
```diff
@@ -88,7 +88,11 @@ export class PaletteContainer extends Component {
   }
 
   generateRandomHex = () => {
-    return '#' + Math.floor(Math.random() * 16777215).toString(16);
+    let hexCode = '#' + Math.floor(Math.random() * 16777215).toString(16);
+      if(hexCode.length < 7 ) {
+        return this.generateRandomHex()
+      }
+    return hexCode;
```
Comment (sschipke) [inline src/components/PaletteContainer/PaletteContainer.js:95]: A bit of simple recursion here. Checking the length of the string to make sure it is 7 characters long. Otherwise leading 0s were disregarded and the function was returning incomplete hex codes.
